const universitiesOfSomalia = [
    {"domains": ["amouduniversity.org"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.amouduniversity.org/"], "name": "Amoud University", "state-province": null},
    {"domains": ["benadiruniversity.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.benadiruniversity.net/"], "name": "Benadir University", "state-province": null}, 
    {"domains": ["bosasocollege.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.bosasocollege.com/"], "name": "Bosaso College", "state-province": null}, 
    {"domains": ["buraouniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.buraouniversity.com/"], "name": "University of Burao", "state-province": null}, 
    {"domains": ["eastafricauniversity.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.eastafricauniversity.net/"], "name": "East Africa University Bosaso", "state-province": null}, 
    {"domains": ["eastsomaliauniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.eastsomaliauniversity.com/"], "name": "East Somalia University", "state-province": null}, 
    {"domains": ["eelouniversity.org"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.eelouniversity.org/"], "name": "Eelo American University", "state-province": null}, 
    {"domains": ["gollisuniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.gollisuniversity.com/"], "name": "Gollis University", "state-province": null}, 
    {"domains": ["hargeisauniversity.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.hargeisauniversity.net/"], "name": "University of Hargeisa", "state-province": null}, 
    {"domains": ["hiiraanuniversity.info"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.hiiraanuniversity.info/"], "name": "Hiiraan University", "state-province": null}, 
    {"domains": ["maakhiruniversity.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://maakhiruniversity.net/"], "name": "Maakhir University", "state-province": null}, 
    {"domains": ["mogadishuuniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.mogadishuuniversity.com/"], "name": "Mogadishu University", "state-province": null}, 
    {"domains": ["nugaaluniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.nugaaluniversity.com/"], "name": "Nugaal University", "state-province": null}, 
    {"domains": ["puntlandstateuniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.puntlandstateuniversity.com/"], "name": "Puntland State University", "state-province": null}, 
    {"domains": ["sanaaguniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.sanaaguniversity.com/"], "name": "Sanaag University of Science and Technology", "state-province": null}, 
    {"domains": ["somtech.org"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.somtech.org/"], "name": "Somaliland University of Technology", "state-province": null}, 
    {"domains": ["universityofsomalia.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.universityofsomalia.net/"], "name": "University of Somalia", "state-province": null}, 
    {"domains": ["amouduniversity.org"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.amouduniversity.org/"], "name": "Amoud University", "state-province": null}, 
    {"domains": ["benadiruniversity.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.benadiruniversity.net/"], "name": "Benadir University", "state-province": null}, 
    {"domains": ["bosasocollege.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.bosasocollege.com/"], "name": "Bosaso College", "state-province": null}, 
    {"domains": ["buraouniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.buraouniversity.com/"], "name": "University of Burao", "state-province": null}, 
    {"domains": ["eastafricauniversity.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.eastafricauniversity.net/"], "name": "East Africa University Bosaso", "state-province": null}, 
    {"domains": ["eastsomaliauniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.eastsomaliauniversity.com/"], "name": "East Somalia University", "state-province": null}, 
    {"domains": ["eelouniversity.org"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.eelouniversity.org/"], "name": "Eelo American University", "state-province": null}, 
    {"domains": ["gollisuniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.gollisuniversity.com/"], "name": "Gollis University", "state-province": null}, 
    {"domains": ["hargeisauniversity.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.hargeisauniversity.net/"], "name": "University of Hargeisa", "state-province": null}, 
    {"domains": ["hiiraanuniversity.info"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.hiiraanuniversity.info/"], "name": "Hiiraan University", "state-province": null}, 
    {"domains": ["maakhiruniversity.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://maakhiruniversity.net/"], "name": "Maakhir University", "state-province": null}, 
    {"domains": ["mogadishuuniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.mogadishuuniversity.com/"], "name": "Mogadishu University", "state-province": null}, 
    {"domains": ["nugaaluniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.nugaaluniversity.com/"], "name": "Nugaal University", "state-province": null}, 
    {"domains": ["puntlandstateuniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.puntlandstateuniversity.com/"], "name": "Puntland State University", "state-province": null}, 
    {"domains": ["sanaaguniversity.com"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.sanaaguniversity.com/"], "name": "Sanaag University of Science and Technology", "state-province": null}, 
    {"domains": ["somtech.org"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.somtech.org/"], "name": "Somaliland University of Technology", "state-province": null},
    {"domains": ["universityofsomalia.net"], "alpha_two_code": "SO", "country": "Somalia", "web_pages": ["http://www.universityofsomalia.net/"], "name": "University of Somalia", "state-province": null}
]

//console.log(universitiesOfSomalia[15].name)
universitiesOfSomalia.forEach(uni=>console.log(`Website: ${uni.web_pages} , Name: ${uni.name}`))